### ISSUE TITLE
Create thethings.IO webhook template

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-webhook-templates#11]
#### Summary
Webhook template for thethings.IO Webhook integration.

#### Can you do this yourself and submit a Pull Request?
Yes

**Comment by nejraselimovic** [comment]
@adriansmares When creating a Webhook integration with thethings.iO, `baseURL` should be set to the (modified) `Callback URL` from thethings.iO. You get this URL in the details of the "product" you created there. 

![callbackurl](https://user-images.githubusercontent.com/65215579/104567362-fdc64780-564e-11eb-8f04-ff75cb41f2c1.png)

In this example, the callback URL is `https://subscription.thethings.io/lora/28752/3Y8Z7ZpVvfu-gw?idname={DevEUI} `. So there are two problems with creating the `baseURL` for the Webhook template:

- `28752` is the product ID (which user can simply provide), but this value `3Y8Z7ZpVvfu-gw` is something auto-generated and I don't see it ascribed to any specific parameter on thethings.iO. Hence, telling a user to fetch that value specifically is just complicating stuff.

- Also, `{DevEUI}` needs to be replaced with `end_device_ids.dev_eui`.

Is there any way a user can provide the callback URL in some Webhook template field, and that replacing the `{DevEUI}` with `end_device_ids.dev_eui` happens in the template?

We had a similar problem with Ubidots, where they provide the final callback URL and telling a user to just paste that URL in the `baseURL` field would be the simplest. Since the `baseURL` needs to be absolute, that was a no-go, but that issue was solvable because all the values from their callback URL had some actual meaning (username, function name), which is not a case here :/

Any ideas?

**Comment by adriansmares** [comment]
I don't think that it should be `{end_device_ids.dev_eui}`, [docs](https://www.thethingsindustries.com/docs/integrations/webhooks/path-variables/) say `devEUI`. Can we ask `thethings.io` to use lower case `d` ?

Then we could just use the URL from them as base URL and an empty uplink path.
