### ISSUE TITLE
Idea: order templates.yml alphabetically

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-webhook-templates#24]
#### Summary

From what I can see the TTS console uses the order of tamplates in templates.yml as the draw order.

Ordering these templates alphabetically will be more fair, and more user friendly.

```
- ubidots
- datacake
- tago
- akenza
- thingspeak
- qubitro
- thethingsio
```
![image](https://user-images.githubusercontent.com/948278/112133027-ecac3080-8bd3-11eb-9f6a-12acb725e223.png)

#### Environment
- **Webhook template:** enter
- **The Things Stack version:** v3.11.3

#### Steps to Reproduce

NA

#### What do you see now?

The templates are listed in the order in which they were added.

#### What do you want to see instead?

Order the templates alphabetically.

#### How do you propose to implement this?

* Manually re-order the templates.yml file
* Change The Things Stack's code to ignore the order in templates.yml and always order alphabetically.

#### Can you do this yourself and submit a Pull Request?

Yes, but this requires a discussion.

**Comment by nejraselimovic** [comment]
Good one @jpmeijers! I'll pick this up
