### ISSUE TITLE
Pull Request Created workflow

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-webhook-templates#28]
#### Summary

We need a better workflow for when pull requests are created.

#### What is already there? What do you see now?

https://github.com/TheThingsNetwork/lorawan-webhook-templates/pull/26 went unnoticed for over a week. While we do have a GitHub Actions workflow for adding the triage label to new issues, we don't have a workflow for adding it to pull requests. Since the CODEOWNERS file doesn't set any reviewers, we also don't automatically request review for pull requests.

#### What is missing? What do you want to see?

Some workflow to request triage or review of pull requests.

#### How do you propose to implement this?

Either:

- a GitHub action that adds the triage label (do we even check PRs with that label?)

or

- set the @TheThingsNetwork/integration-maintainers team as code-owner of this repository.

**Comment by nejraselimovic** [comment]
@htdvisser I agree, this was on my mind when I accidentally noticed #26 last week. I will try to pick this up asap
