### ISSUE TITLE
Create Wonderland webhook template

### ISSUE THREAD

**Issue by gitahubbit** [TheThingsNetwork/lorawan-webhook-templates#53]
#### Summary
We'd like to add an integration for our IoT platform Wonderland which focuses on tracking applications.

#### Why do we need this?
This will expand the potential use of both our and your platform and TheThingsNetwork

#### Environment
We're mostly using PHP for connectivity integrations, sometimes Python. In this case we'll use PHP with Slim

#### How do you propose to implement this?
We already implemented TTN support for both V2 and V3 stacks. The only thing missing is an easy-to-use integration template for our users. Implementation will likely be a no-brainer as all the JSON decoding etc. is already in place.

#### Can you do this yourself and submit a Pull Request?
We're using GitLab on our end, but I guess things will be just as easy with GitHub

**Comment by gitahubbit** [comment]
Hi @nejraselimovic , how shall we proceed from here? Will you create a branch for the wonderland integration?

**Comment by nejraselimovic** [comment]
Hi @gitahubbit, nice to see your interesting in submitting a Webhook template.

You can create a branch on your own, follow [this](https://www.thethingsindustries.com/docs/integrations/webhooks/webhook-templates/) to create a template, then create a pull request and tag me as a reviewer. If you have trouble with the process, you can always send me the template you created, I can create the PR for you. I can also test things on our end but I would need a free access to your platform for that.

You can also submit the integration guide in our [documentation repository](https://github.com/TheThingsIndustries/lorawan-stack-docs). Again, if you have trouble with the process, you can send me the content and I'll push it for you.

**Comment by gitahubbit** [comment]
Hi Nejra,

Thanks for getting back to me.

I created a local branch issue/wonderland-webhook and would like to push  
it to origin, but get an "access denied" error.
Without pushing it to your repo I don't know how to create the pull  
request. Apologies for my ignorance in case I am missing something.

Best regards,
Andreas

PS: I think it it would be great if we manage to follow your deployment  
process in the right way, so we'll be able to push changes in the future



On Wed, 02 Feb 2022 11:32:03 +0100, Nejra Selimović  
***@***.***> wrote:

>
> Hi @gitahubbit, nice to see your interesting in submitting a Webhook  
> template.
>
> You can create a branch on your own, follow this to create a template,  
> then create a pull request and tag me as a reviewer. If you have  
> >trouble with the process, you can always send me the template you  
> created, I can create the PR for you. I can also test things on our end  
> >but I would need a free access to your platform for that.
>
> You can also submit the integration guide in our documentation  
> repository. Again, if you have trouble with the process, you can send me  
> the >content and I'll push it for you.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.You  
> are receiving this because you were mentioned.



-- 
Andreas Senn
Bühlwiesenstrasse 10
8052 Zürich, Schweiz
+41 76 7000736

**Comment by nejraselimovic** [comment]
> Hi Nejra, Thanks for getting back to me. I created a local branch issue/wonderland-webhook and would like to push it to origin, but get an "access denied" error. Without pushing it to your repo I don't know how to create the pull request. Apologies for my ignorance in case I am missing something. Best regards, Andreas PS: I think it it would be great if we manage to follow your deployment process in the right way, so we'll be able to push changes in the future

Of course, let's see if we can solve this. Can you please tell me what you see when you list remotes with `git remote -v`? I think this is on your end, keys or something, because I just managed a PR created by someone else from the community.

**Comment by gitahubbit** [comment]
Hi again Nejra,

I've now cloned your templates repo, committed my changes and filed a pull  
request to your master branch
https://github.com/TheThingsNetwork/lorawan-webhook-templates/pull/54

This procedure appears to work. How about your end?

Best regards,
Andreas



On Wed, 02 Feb 2022 14:12:59 +0100, Nejra Selimović  
***@***.***> wrote:

>>
>> Hi Nejra, Thanks for getting back to me. I created a local branch  
>> issue/wonderland-webhook and would like to push it to origin, >>but get  
>> an "access denied" error. Without pushing it to your repo I don't know  
>> how to create the pull request. Apologies for my >>ignorance in case I  
>> am missing something. Best regards, Andreas PS: I think it it would be  
>> great if we manage to follow your >>deployment process in the right  
>> way, so we'll be able to push changes in the future
>
> Of course, let's see if we can solve this. Can you please tell me what  
> you see when you list remotes with git remote -v? I think this is >on  
> your end, keys or something, because I just managed a PR created by  
> someone else from the community.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.You  
> are receiving this because you were mentioned.



-- 
Andreas Senn
Bühlwiesenstrasse 10
8052 Zürich, Schweiz
+41 76 7000736

**Comment by nejraselimovic** [comment]
> Hi again Nejra, I've now cloned your templates repo, committed my changes and filed a pull request to your master branch #54 This procedure appears to work. How about your end? Best regards, Andreas

Yes, this looks perfect! I'll give it a review by tomorrow

**Comment by gitahubbit** [comment]
Great :) Thanks a lot and have a nice evening!

On Wed, 02 Feb 2022 16:20:20 +0100, Nejra Selimović  
***@***.***> wrote:

>>
>> Hi again Nejra, I've now cloned your templates repo, committed my  
>> changes and filed a pull request to your master branch #54 >>This  
>> procedure appears to work. How about your end? Best regards, Andreas
>
> Yes, this looks perfect! I'll give it a review by tomorrow
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.You  
> are receiving this because you were mentioned.



-- 
Andreas Senn
Bühlwiesenstrasse 10
8052 Zürich, Schweiz
+41 76 7000736
