### ISSUE TITLE
Update Cloud Studio logo

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-webhook-templates#83]
Cloud Studio asked to change their logo. They sent it to me by email, @adriansmares can we host it somewhere to be linked in the template?
![cloudstudio-logo-PNG-gradiente](https://github.com/TheThingsNetwork/lorawan-webhook-templates/assets/65215579/aa91ff33-a199-4d53-900f-54f017854d71)

**Comment by nejraselimovic** [comment]
I just found out they have it hosted here https://www.cloud.studio/wp-content/uploads/2022/04/cloudstudio-logo-SVG-gradiente.svg, will this work?

**Comment by KrishnaIyer** [comment]
I'm not sure. Maybe @adriansmares?

**Comment by adriansmares** [comment]
We currently link external links for most logos, so this should be fine as long as it renders in a local stack.
